apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.db.service.name }}
  labels:
    name: {{ .Values.global.appname }}
    app: {{ .Values.global.appname }}
spec:
  type: {{ .Values.db.service.type }}
  ports:
    - port: {{ .Values.db.service.port }}
      targetPort: {{ .Values.db.service.targetport }}
      protocol: TCP
      name: {{ .Values.db.service.portname }}
  selector:
    app: {{ .Values.global.selector.name }}
    component: {{ .Values.db.componentname }}
