apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.fe.server.name }}
  labels:
    release: {{ .Values.global.appname }}
    app: {{ .Values.global.appname }}
    component: {{ .Values.fe.component.name }}
spec:
  replicas: {{ .Values.fe.server.replicas }}
  selector:
    matchLabels:
      release: {{ .Values.global.appname }}
      app: {{ .Values.global.appname }}
      component: {{ .Values.fe.component.name }}
  template:
    metadata:
      labels:
        release: {{ .Values.global.appname }}
        app: {{ .Values.global.appname }}
        component: {{ .Values.fe.component.name }}
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            - labelSelector:
                matchLabels:
                  app: {{ .Values.global.appname }}
                  release: {{ .Values.global.appname }}
                  component: {{ .Values.fe.component.name }}
              topologyKey: kubernetes.io/hostname
      terminationGracePeriodSeconds: 60
      volumes:
        - name: kubestriker-python-storage
          emptyDir: {}
      containers:
        - name: {{ .Values.fe.server.image.name }}
          image: "{{ .Values.fe.server.image.repository }}"
          imagePullPolicy: {{ .Values.fe.server.image.pullPolicy }}
          env:
            - name: ADVERTISE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: NAMSESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: API_URL
              value: {{ .Values.fe.server.apiaddress }}
          ports:
            - name: {{ .Values.fe.service.name }}
              containerPort: 80
              protocol: TCP
            - name: python-server
              containerPort: 8888
              protocol: TCP
          volumeMounts:
            - name: kubestriker-python-storage
              mountPath: /data
              subPath: data
